mysite/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()
urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'blog.views.home', name='home'),
    # url(r'^mysite/', include('mysite.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += patterns(('blog.views'),
    url(r'^blog/$', 'blog_list', name = 'bloglist'),
    url(r'^blog/blog/(?P<id>\d+)/$', 'blog_show', name = 'detailblog'),
    url(r'^search$', 'search', name = 'search'),
    url(r'^blog/tag/(?P<id>\d+)/$', 'search_tag', name='searchtag'),
    url(r'^blog/add/$', 'blog_add', name='addblog'),
    url(r'^blog/(?P<id>\d+)/update/$', 'blog_update', name='updateblog'),
    url(r'^blog/(?P<id>\w+)/del/$', 'blog_del', name='delblog'),
    url(r'^login/$', 'login', name = 'login'),
    url(r'^logout/$', 'logout', name = 'logout'),
)

urlpatterns += patterns((''),
    (r'^static/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': 'static'}  
    ),
)

blog/models.py
from django.db import models


class Tag(models.Model):
    """docstring for Tags"""
    tag_name = models.CharField(max_length=20, blank=True)
    create_time = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.tag_name


class Author(models.Model):
    """docstring for Author"""
    name = models.CharField(max_length=30)
    email = models.EmailField(blank=True)
    website = models.URLField(blank=True)

    def __unicode__(self):
        return u'%s' % (self.name)


class Blog(models.Model):
    """docstring for Blogs"""
    caption = models.CharField(max_length=50)
    author = models.ForeignKey(Author)
    tags = models.ManyToManyField(Tag, blank=True)
    content = models.TextField()
    publish_time = models.DateTimeField(auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return u'%s %s %s' % (self.caption, self.author, self.publish_time)

    class Meta:
        ordering = ['-publish_time']

blog/forms.py
from django import forms

class BlogForm(forms.Form):
    """docstring for BlogForm"""
    caption = forms.CharField(label='title', max_length=100)
    content = forms.CharField(widget=forms.Textarea)

class TagForm(forms.Form):
  """docstring for TagForm"""
  tag_name = forms.CharField()

class LoginForm(forms.Form):
  username=forms.CharField(label="username",max_length=30,
    widget=forms.TextInput(attrs={'size': 20,}))
  password=forms.CharField(label="password",max_length=30,
    widget=forms.PasswordInput(attrs={'size': 20,}))

blog/views.py
# Create your views here.
from django.shortcuts import render_to_response
from blog.models import *
from blog.forms import *
from django.http import Http404
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.template import RequestContext
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.contrib.auth.models import User

def blog_list(request):
  """docstring for blog_list"""
  blogs = Blog.objects.all()
  tags  = Tag.objects.all()
  htext = "Blogs"
  return render_to_response("blog_list.html", 
    {"blogs": blogs, "htext": htext, "tags": tags, "user": request.user})

def blog_show(request, id = ''):
 """docstring for blog_show"""
 try:
   blog = Blog.objects.get(id = id)
 except Blog.DoesNotExist:
   raise Http404
 return render_to_response("blog_show.html", {"blog": blog, "user": request.user})

def home(request):
  """docstring for home"""
  latest = Blog.objects.order_by("-publish_time")[0:3]
  return render_to_response("home.html", {"latest": latest})

def search(request):
  key   = request.GET.get('q')
  blogs = Blog.objects.filter(Q(caption__icontains=key) | Q(content__icontains=key))
  tags  = Tag.objects.all()
  htext = "Search"
  return render_to_response("blog_list.html", {"blogs": blogs, "htext": htext, "tags": tags})

def search_tag(request, id = ''):
  tag   = Tag.objects.get(id = id)
  tags  = Tag.objects.all()
  blogs = tag.blog_set.all()
  htext = "Search by Tag"
  return render_to_response("blog_list.html", {"blogs": blogs, "htext": htext, "tags": tags})

def blog_add(request):
  if not request.user.is_authenticated():
      return HttpResponseRedirect("/blog/")
  if request.method == 'POST':
    form = BlogForm(request.POST)
    tag  = TagForm(request.POST)
    if form.is_valid() and tag.is_valid():
      data     = form.cleaned_data
      data_tag = tag.cleaned_data
      tagname  = data_tag['tag_name']
      for taglist in tagname.split():
        Tag.objects.get_or_create(tag_name = taglist.strip())
      title    = data['caption']
      author   = Author.objects.get(id=1)
      content  = data['content']
      blog     = Blog(caption=title, author=author, content=content)
      blog.save()
      for taglist in tagname.split():
        blog.tags.add(Tag.objects.get(tag_name = taglist.strip()))
        blog.save()
      id       = Blog.objects.order_by('-publish_time')[0].id
      return HttpResponseRedirect('/blog/blog/%s' % id)
  
  form = BlogForm()
  tag  = TagForm()
  return render_to_response('blog_add.html', {'form': form, 'tag': tag}, 
                            context_instance=RequestContext(request))

def blog_update(request, id=""):
  if not request.user.is_authenticated():
      return HttpResponseRedirect("/blog/")
  id = id
  if request.method == 'POST':
    form = BlogForm(request.POST)
    tag = TagForm(request.POST)
    if form.is_valid() and tag.is_valid():
      cd = form.cleaned_data
      cdtag = tag.cleaned_data
      tagname = cdtag['tag_name']
      tagnamelist = tagname.split()
      for taglist in tagnamelist:
        Tag.objects.get_or_create(tag_name=taglist.strip())
      title = cd['caption']
      content = cd['content']
      blog = Blog.objects.get(id=id)
      if blog:
        blog.caption = title
        blog.content = content
        blog.save()
        for taglist in tagnamelist:
          blog.tags.add(Tag.objects.get(tag_name=taglist.strip()))
          blog.save()
        tags = blog.tags.all()
        for tagname in tags:
          tagname = unicode(str(tagname), "utf-8")
          if tagname not in tagnamelist:
            notag = blog.tags.get(tag_name=tagname)
            blog.tags.remove(notag)
      else:
        blog = Blog(caption=blog.caption, content=blog.content)
        blog.save()
      return HttpResponseRedirect('/blog/blog/%s' % id)

  try:
      blog = Blog.objects.get(id=id)
  except Exception:
      raise Http404
  form = BlogForm(initial={'caption': blog.caption, 'content': blog.content})
  tags = blog.tags.all()
  if tags:
      taginit = ''
      for x in tags:
          taginit += str(x) + ' '
      tag = TagForm(initial={'tag_name': taginit})
  else:
      tag = TagForm()
  return render_to_response('blog_add.html',
      {'blog': blog, 'form': form, 'id': id, 'tag': tag},
      context_instance=RequestContext(request))

def blog_del(request, id=""):
  if not request.user.is_authenticated():
      return HttpResponseRedirect("/blog/")
  try:
    blog = Blog.objects.get(id=id)
  except Exception:
    raise Http404
  if blog:
    blog.delete()
    return HttpResponseRedirect("/blog/")
  blogs = Blog.objects.all()
  return render_to_response("blog_list.html", {"blogs": blogs})

def login(request):
  if request.method == 'POST':
    form = LoginForm(request.POST)
    if form.is_valid():
      data = form.cleaned_data
      user=authenticate(username=data['username'],password=data['password'])
      auth_login(request, user)
      return HttpResponseRedirect("/blog/")

  form = LoginForm()
  return render_to_response('login.html', {'form': form}, context_instance=RequestContext(request))

def logout(request):
  auth_logout(request)
  return HttpResponseRedirect("/blog/")

templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <link rel='stylesheet' href="/static/css/bootstrap.min.css" />
    <link href='/static/css/style.css' rel='stylesheet' />
    <script src='/static/js/jquery-1.9.1.min.js' type='text/javascript'></script>
    <script src='/static/js/bootstrap.min.js' type='text/javascript'></script>
    <title>
      {% block title %} {% endblock %}
    </title>
    {% block extra_head %}
    {% endblock %}
  </head>
  <body>
    {% block body %}
      {% block header %}
        
      {% endblock %}
      <div class='container'>
        {% block content %}
          
        {% endblock %}

        {% block footer %}
          
        {% endblock %}
      </div>
    {% endblock %}
  </body>
</html>

templates/blog/blog_add.html
{% extends "blog_base.html" %}

{% block title %}
Add New Blog
{% endblock title %}

{% block content %}
<div class="row-fluid">

    <form action="" method="post">
        {% csrf_token %} 
        <div class="span8 offset3">
            <div class="field">
                <label for="id_caption">Title: </label>
                {% if form.caption.errors %}
                <div class="alert alert-error">
                    {{ form.caption.errors }}          
                </div>
                {% endif %}
                {{ form.caption }}
            </div>
            <div class="field">
                <label for="id_tag">Tags</label>
                {% if tag.tag_name.errors %}
                <div class="alert alert-error">
                    {{ tag.tag_name.errors }}
                </div>
                {% endif %}
                {{ tag.tag_name }}
            </div>
            <div class="field">        
                <label for="id_content">Content: </label>
                {% if form.content.errors %}
                <div class="alert alert-error">
                    {{ form.content.errors }}
                </div>
                {% endif %}
                {{ form.content }}
            </div>
            <input class="btn btn-primary" type="submit" value="save and add">
        </div>
    </form>
</div>
{% endblock content %}

templates/blog/blog_list.html
{% extends "blog_base.html" %}

{% block title %} blog list {% endblock %}

{% block content %}
<div class='content-main'>
  <section>
    <ul class="breadcrumb">
      <li><a href="/">Home</a><span class="divider">/</span></li>
      <li class="active"> {{htext}} </li>
    </ul>
    <div class="page-header">
      <h1> {{htext}} </h1>
      <p class='muted'>{{ blogs.count }} results</p>      
    </div>
  </section>
  <div class="row-fluid">
    <div class="span9">
      {% for blog in blogs%}
      <div class="blog-entry">
        <h3>
          <a href = "{% url "detailblog" blog.id %}"> {{ blog.caption }} </a>
        </h3>

        <p class="muted">
          <i class="icon-user"></i><small> {{ blog.author }} </small>
        </p>

        <div class='content'>
          {{ blog.content|linebreaksbr }}
        </div>

        <footer class='muted blog-footer'>
          <p>
            {% for tag  in blog.tags.all  %}
              <a class='muted' href="{% url "searchtag" tag.id%}">
                <i class='icon-tag'></i>
                <small>{{ tag }}</small>
              </a> 
           {% endfor %}        
          </p>
          <p><i class="icon-time"></i><small>{{ blog.publish_time.date }}</small></p>
          
        </footer>
      </div>
      {% endfor %}
    </div>
    <div class="span2" id="aside">
      {% if user.is_authenticated %}
        <a class="btn" href="{% url "addblog" %}"><i class="icon-plus"></i>New Blog</a>
      {% endif %}
      <h3>Tags</h3>
      {% for tag in tags %}
        <p>
          <span><a href="{% url "searchtag" tag.id%}">{{ tag }}</a></span>
        </p>
      {% endfor%}
      <h3>Utilities</h3>
      {% if not user.is_authenticated %}
        <a href="{% url "login" %}">login</a>
      {% else %}
        <a href="{% url "logout" %}">logout</a>
      {% endif %}
    </div>
  </div>

</div>
{% endblock%}

templates/blog/blog_show.html
{% extends "blog_base.html" %}

{% block title %}{{ blog.caption }}{% endblock%}

{% block content%}
<div class="blog-entry">

  <div class="blog-header">

    <ul class="breadcrumb">
      <li><a href="/">Home</a><span class="divider">/</span></li>
      <li><a href="/blog">Blogs</a><span class="divider">/</span></li>
      <li class="active"> {{ blog.caption }} </li>
    </ul>

    <div class="page-header text-center" style="margin-top: 50px;">
      <h1>{{ blog.caption }} </h1>
      <i class="icon-user"></i><small> {{ blog.author }} </small>
    </div>
  </div>

  <div class='content'>
    {{ blog.content|linebreaksbr }}
  </div>

  <footer class='blog-footer row-fluid post-info'>
    <div class="span3 muted">
      <p>
        {% for tag  in blog.tags.all  %}
        <a class='muted' href="{% url "searchtag" tag.id%}">
          <i class='icon-tag'></i>
          <small>{{ tag }}</small>
        </a> 
        {% endfor %}        
      </p>
      <p>
        <i class="icon-time"></i><small>{{ blog.publish_time.date }}
      </p>
    </div>
    {% if user.is_authenticated %}      
      <div class="span2 offset7 text-right">
        <a href="{% url "delblog" blog.id %}" title="delete"><i class="icon-trash"></i></a> 
        <a href="{% url "updateblog" blog.id %}" title="edit"><i class="icon-edit"></i></a>
      </div>    
    {% endif %}
   </footer>
 </div>
 {% endblock%}

templates/blog/home.html
{% extends 'blog_base.html' %}

{% block content %}
<div class='row'>
  <div class='span8'>
    <h1>Doraemon</h1>
    <p class='lead'>
       I am a robotic cat named Doraemon. <br>
       I traveled back in time from the 22nd century. <br>
       I am aiding a pre-teen boy called Nobita Nobi. <br>
    </p>
    <div class="c-cta">
      <div class='btn-group'>
        <a href='/blog' class='btn btn-info btn-large'>View My Blogs</a>
      </div>
    </div>
  </div>
  <div class='span4'>
    <img src="/static/img/avatar.jpg" alt="tuts hub" />
  </div>
</div>
<div class="container" style="margin-top:10px;">
  <h3>My Recent Blogs</h3>
  <div id="testimonials" class="carousel slide">

      <ol class="carousel-indicators">
        <li data-target="#testimonials" data-slide-to="0" class="active"></li>
        <li data-target="#testimonials" data-slide-to="1"></li>
        <li data-target="#testimonials" data-slide-to="2"></li>
      </ol>

      <div class="carousel-inner">
        {% for blog in latest %}
          <div class="item {% if blog == latest.0 %}active{% endif %}">
            <h4 >
              <a href = "{% url "detailblog" blog.id %}"> {{ blog.caption }} </a>
            </h4>
          </div>
        {% endfor %}
      </div>

    </div>
</div>
{% endblock %}

templates/blog/login.html
{% extends "blog_base.html" %}

{% block title %}Login{% endblock title %}

{% block content %}
<div class="row-fluid">

    <form action="" method="post">
        {% csrf_token %} 
        <div class="span8 offset3">
            <div class="field">
                <label for="id_username">Username: </label>
                {% if form.username.errors %}
                <div class="alert alert-error">
                    {{ form.username.errors }}          
                </div>
                {% endif %}
                {{ form.username }}
            </div>
            <div class="field">        
                <label for="id_password">Password: </label>
                {% if form.password.errors %}
                <div class="alert alert-error">
                    {{ form.password.errors }}
                </div>
                {% endif %}
                {{ form.password }}
            </div>
            <input class="btn btn-primary" type="submit" value="login">
        </div>
    </form>
</div>
{% endblock content %}

templates/blog_base.html
{% extends "base.html" %}

{% block header %}
<div class='navbar navbar-inverse navbar-fixed-top'>
  <div class='navbar-inner'>
    <div class='container'>
      <a href='/' class='brand'>Django Blog</a>

      <a data-toggle='collapse' data-target='.nav-collapse' class='btn btn-navbar'>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
      </a>

      <div class='collapse nav-collapse'>

        <form action='/search' class='navbar-search pull-right' method='get'>
          <input type='text' class='search-query' placeholder='Searching...' name='q'/>
        </form>

        <ul class='nav pull-right'>
          <li> <a href='/'>Home</a> </li>
          <li> <a href='/blog/'>Archive</a> </li>
        </ul>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block footer %}
<section class="text-center footer">
<p class="lead">Wanna get more touch? Email at <a href="mailto:abc@def.hi">abc@def.hi</a></p>

<ul class="inline">
  <li><strong>Follow me on:</strong></li>
  <li><a href="">Twitter</a></li>
  <li><a href="">Facebook</a></li>
</ul>

<p class="muted">Powered by Django and Bootstrap</p>
</section>
{% endblock %}